export const API_USER_DATA_KEY = 'api_user_data_secret_key'
export const DATABASE_USER = 'database_user'
export const DATABASE_PASSWORD = 'database_password'
export const DATABASE_HOST = 'database_host'
export const DATABASE_PORT = 'database_port'
export const DATABASE_NAME = 'database_name'
export const DATABASE_TABLE_NAME = 'database_name'
